export default [
  {
    complete: false,
    completeWithHelp: false,
    correctSelector: 'plate',
    name: 'Type',
    description: 'Select plate by type',
    markup: ['<plate class="--selected">'],
  },
  {
    complete: false,
    completeWithHelp: false,
    correctSelector: '#sweet',
    name: 'ID',
    description: 'Select sweet cookie on plate',
    markup: ['<plate>', '<cookie id = "sweet" class="--selected">', '</cookie>', '</plate>'],
  },
  {
    complete: false,
    completeWithHelp: false,
    correctSelector: '.fancy',
    name: 'Class',
    description: 'Select fancy plate by class',
    markup: [
      '<plate>',
      '</plate>',
      '<plate class = "fancy --selected">',
      '</plate>',
      '<plate>',
      '</plate>',
    ],
  },
  {
    complete: false,
    completeWithHelp: false,
    name: 'Data attribute',
    correctSelector: 'apple[data-color="red"]',
    description: 'Select red apple by data attribute',
    markup: [
      '<plate>',
      '<apple data-color="red" class="--selected">',
      '</apple>',
      '</plate>',
      '<plate>',
      '<apple data-color="green">',
      '</apple>',
      '</plate>',
    ],
  },
  {
    complete: false,
    completeWithHelp: false,
    correctSelector: '*',
    name: 'Universal selector',
    description: 'Select everything by universal selector',
    markup: [
      '<plate class="--selected">',
      '<apple data-color="red" class="--selected">',
      '</apple>',
      '</plate>',
      '<plate class="--selected">',
      '<apple data-color="green" class="--selected">',
      '</apple>',
      '</plate>',
    ],
  },
  {
    complete: false,
    completeWithHelp: false,
    correctSelector: 'cookie, apple',
    name: 'Grouping selector',
    description: 'Select cookie and apple by grouping selector',
    markup: [
      '<plate>',
      '<cookie class="--selected">',
      '</cookie>',
      '<apple class="--selected">',
      '</apple>',
      '</plate>',
    ],
  },
  {
    complete: false,
    completeWithHelp: false,
    correctSelector: '.fancy > cookie',
    name: 'Child combinator',
    description: 'Select cookie in fancy plate',
    markup: [
      '<plate>',
      '<cookie>',
      '</cookie>',
      '</plate>',
      '<plate class = "fancy">',
      '<cookie class="--selected">',
      '</cookie>',
      '</plate>',
      '<plate>',
      '<cookie>',
      '</cookie>',
      '</plate>',
    ],
  },
  {
    complete: false,
    completeWithHelp: false,
    correctSelector: 'cookie ~ apple',
    name: 'General sibling combinator',
    description: 'Select aple after cookie',
    markup: [
      '<plate>',
      '<cookie>',
      '</cookie>',
      '<apple class="--selected">',
      '</apple>',
      '</plate>',
    ],
  },
  {
    complete: false,
    completeWithHelp: false,
    correctSelector: 'plate > :first-child',
    name: 'First child pseudo-class',
    description: 'Select first child of plate',
    markup: [
      '<plate class="fancy">',
      '<cookie class="--selected">',
      '</cookie>',
      '<apple>',
      '</apple>',
      '</plate>',
    ],
  },
  {
    complete: false,
    completeWithHelp: false,
    correctSelector: 'plate > :last-child',
    name: 'Last child pseudo-class',
    description: 'Select last child of plate',
    markup: [
      '<plate class="big">',
      '<cookie>',
      '</cookie>',
      '<apple>',
      '</apple>',
      '<cookie>',
      '</cookie>',
      '<apple>',
      '</apple>',
      '<cookie>',
      '</cookie>',
      '<apple class="--selected">',
      '</apple>',
      '</plate>',
    ],
  },
];
